name: eShopOnWeb Build and Tests

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: az400m03l07-RG
  LOCATION: WestUS2 
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 0e840818-c4b4-4569-9335-ebd9b5c7b194

jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      #checkout the repository
      - uses: actions/checkout@v5
      #prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"
      #Build/Test/Publish the .net project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .
      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      #Download the publish files created in previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: .net-app
          path: .net-app

      #Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Publish website to Azure App Service (WebApp)
      # Step disabled due to issue where the site sometimes can't be found: https://github.com/microsoft/pipelines-appservice-lib/issues/56. Instead deploy using CLI
      - name: Publish Website to WebApp
        if: false #Disable step due to comment above
        uses: Azure/webapps-deploy@v3
        with:
          type: ZIP
          app-name: eshoponwebyaml59356557
          package: .net-app/app.zip

      # Publish website to Azure App Service using CLI (WebApp)
      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name eshoponwebyaml59356557 --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip
